### ISSUE TITLE
链表方法 indexOf逻辑有误

### ISSUE THREAD

**Issue by jimwmg** [Lxxyx/LearnDataStructrue#3]
`this.indexOf = function(element) {
    var current = head;
    var index = -1;  //这里应该为0 吧

    while (current) {
      if (element === current.element) {
        return index;
      }
      index++;
      current = current.next;
    }

    return -1;
  };

`var list = new LinkedList();
function f(){
    console.log('fff')
}
list.append(f);
console.log(list.indexOf(f));
    `

**Comment by Lxxyx** [comment]
确实是这样子，已修复，谢谢
